namespace CFD
{
    [bindable]
    runtimeclass NavierStokes: Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        NavierStokes();
        Windows.Foundation.IAsyncActionWithProgress<Windows.Foundation.Collections.IVector<Double> > Solve();
        event Windows.Foundation.EventHandler<NavierStokesEventArgs> IterationCompleted;

        
        Boolean Solved;
        Double Rho;
        Double Nu;

        Double L;
        Double H;
        Double Nx;
        Double Ny;
        Double Dx{ get; };
        Double Dy{ get; };
        Double Re{ get; };

        Double T;
        Double Dt;
        Double Nt{ get; };

        Double Pdtau;
    }

    [default_interface]
    runtimeclass NavierStokesEventArgs
    {
        Double MaximumXi{ get; };
    }
}
